tasks:
  - name: terraform
    before: |
      source ./bin/set_tf_alias.sh
      source ./bin/install_terraform_cli.sh 
      source ./bin/generate_tfrc_credentials.sh
      cp $PROJECT_ROOT/terraform.tfvars_example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/install_aws_cli.sh
  - name: http-server
    before: |
      npm install --global http-server
    command:
      http-server
      
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
    - phil294.git-log--graph
    - mhutchie.git-graph